version: '3.8'

services: 
  postgres:
   image:  postgres:16.4-alpine3.20
   restart: always
   environment:
     POSTGRES_USER: your_username
     POSTGRES_PASSWORD: your_password
     POSTGRES_DB: your_database_name
   ports:
     - "5432:5432"
   volumes:
     - ./data:/var/lib/postgresql/data
