apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app-service
spec:
  type: NodePort
  selector:
    app: k8s-test-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000  # Choose a port in the range 30000-32767

# 1. **Port (80):** This is the port on which the service is exposed internally within the cluster. It's the port that the service listens on, and other services within the cluster would use this port to communicate with the service.
# 2. **TargetPort (3000):** This is the port on the container or pods that the service forwards to. In this setup, traffic arriving at the service on port 80 will be directed to port 3000 on the target pods, which might be where your application is actually listening for incoming traffic.
# 3. **NodePort (30000):** This port is opened on every Node in the Kubernetes cluster, allowing external traffic to reach the service. You can access the service from outside the cluster by sending requests to any Node's IP at the specified `NodePort` (30000 in this case). NodePort values must be manually assigned within the default range of 30000-32767.